name: compspi-vaegan
channels:
  - conda-forge
  - omnia
  - defaults
dependencies:
  - python=3.7
  - hyperopt
  - pandas
  - tabulate
  - requests
  - visdom
  - h5py
  - scikit-image
  - pip
  - pyfftw==0.12.0
  - geomstats==2.2.2
  - pip:
    - ray
    - torch
    - torchvision
