  - uses: actions/checkout@v2
    with:
      ref: ${{ github.event.pull_request.head.sha }}

  - name: Report results to DeepSource
    run: |
    # Generate coverage report in xml format
      coverage xml
   
    # Install deepsource CLI
      curl https://deepsource.io/cli | sh
   
    # From the root directory, run the report coverage command
      ./bin/deepsource report --analyzer test-coverage --key python --value-file ./coverage.xml
      
    env: 
      DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
